# version: "3.9"

services:
  db:
    restart: always
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./postgres-data/db:/var/lib/postgresql/data/:rw
    ports:
      - "8006:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "PGDATA=/var/lib/postgresql/data/"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8009:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: altersense_rpa@altersense.com
      PGADMIN_DEFAULT_PASSWORD: altersense_rpa
    volumes:
      - ./postgres-data/db:/var/lib/postgresql/data
    links:
      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - .:/app/
    ports:
      - "8008:8008"
    depends_on:
      - db
    restart: always
