# Generated by Django 4.2.11 on 2024-04-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('activity', models.TextField(blank=True, default=None, null=True)),
                ('activity_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='purchase_data/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('po_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order_no', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('item', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('country_iso', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('country_name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('no_of_pcs_per_pack', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('quantity_in_pack', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('quantity_in_pcs', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('quantity', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('invoice_average_price', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('currency_iso', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('currency_name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('currency_code', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('delivery_time', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('s_c_no', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('lc_no', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('bin', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('ad_code', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('commodity_code', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('incoterm', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('unit_code', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('area_code', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('invoice_date', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('invoice_amount', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('cmt_amount', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('freight', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('insurance', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('other_charges', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('carrier_vessel', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('dest_port', models.CharField(blank=True, max_length=255)),
                ('trans_doc_type', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('trans_doc_no', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('trans_doc_date', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('ship_port', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('sector', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('fob_amount', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('signatory_id', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('bank_ref_no', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('exp_serial', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('exp_year', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('full_exp', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('issue_date', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('exp_status', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('booking_status', models.CharField(blank=True, default='', max_length=25, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
