# Generated by Django 4.2.11 on 2024-04-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('activity', models.TextField(blank=True, default=None, null=True)),
                ('activity_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
