# Generated by Django 4.2.11 on 2024-04-03 04:56

from django.db import migrations, models
import django.db.models.deletion

from apps.commercial.models import BookingConfig


def add_initial_data():
    BookingConfig.add_initial_data()


class Migration(migrations.Migration):
    try:
        add_initial_data()
    except Exception as e:
        pass
    dependencies = [
        ('commercial', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True,
                 default=None, max_length=255, null=True)),
                ('password', models.CharField(blank=True,
                 default=None, max_length=255, null=True)),
                ('status', models.CharField(blank=True,
                 default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True,
                 default=None, max_length=255, null=True)),
                ('status', models.CharField(blank=True,
                 default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ActivityLogs',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='request_id',
        ),
        migrations.AddField(
            model_name='pobooking',
            name='purchase_order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='commercial.purchaseorder'),
        ),
    ]
