# Generated by Django 4.2.11 on 2024-04-04 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0003_bookingconfig_bookingcredentials_pobooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('summary_marks', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('summary_desc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('no_of_pcs_in_pack', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PoBooking',
        ),
    ]
