# Generated by Django 4.2.11 on 2024-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_purchaseorderbooking_alter_activitylog_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderbooking',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='purchaseorderbooking',
            name='request_id',
            field=models.CharField(blank=True, default='ece1d8afbf8d4a2da5525c231009a6a7', max_length=255, null=True),
        ),
    ]
