# Generated by Django 4.2.11 on 2024-04-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_remove_purchaseorderbooking_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='draft',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderbooking',
            name='request_id',
            field=models.CharField(blank=True, default='bf81303923d54958ae229ec561e278f4', max_length=255, null=True),
        ),
    ]
