# Generated by Django 4.2.11 on 2024-04-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_activitylog_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='request_id',
            field=models.CharField(blank=True, default='adadd762d11e4e51bdfb8e207d23de25', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderbooking',
            name='request_id',
            field=models.CharField(blank=True, default='d6315dcc529540d08710e0437a6748d8', max_length=255, null=True),
        ),
    ]
