# Generated by Django 4.2.11 on 2024-04-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0007_purchaseorder_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='request_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderbooking',
            name='request_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
