# Generated by Django 4.2.11 on 2024-04-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_alter_purchaseorder_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderbooking',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=255, null=True),
        ),
    ]
