# Generated by Django 4.2.11 on 2024-04-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_alter_purchaseorderbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='invoice_data/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
