# Generated by Django 4.2.11 on 2024-04-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_invoicefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('invoice_date', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('exporters_ref', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('hs_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('composition', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('po_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country_iso', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fcr_status', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
