# Generated by Django 4.2.11 on 2024-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0011_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=255, null=True),
        ),
    ]
